android {
   compileSdkVersion 30 // ou superior
  defaultConfig {
    multiDexEnabled true
  }
  compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

buildscript {
  repositories {
    google()
    mavenCentral()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:4.1.0'
    classpath 'com.google.gms:google-services:4.5.0'
    classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.8'
  }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task cleanMyProject(type: Delete) {
    delete rootProject.buildDir
}

repositories {
  google()
  mavenCentral()
  maven {
    url "https://maven.google.com"
  }
}

dependencies {
  implementation 'me.leolin:ShortcutBadger:1.1.22@aar'
  implementation 'com.google.firebase:firebase-auth:23.0.0'
  implementation 'com.google.firebase:firebase-analytics:22.0.2'
  implementation('com.google.firebase:firebase-crashlytics:19.0.3') {
    transitive = true
  }
}

cdvPluginPostBuildExtras.add({
  apply plugin: 'com.google.gms.google-services'
})
